version: '3'
networks:
  testNetwork:
    driver: bridge
services:

  GamePerfDB:
    container_name: BackEnd 
    image: bitnami/postgresql:15
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_USER=admin
      - POSTGRESQL_DATABASE=gameperfdb
    networks:
      - testNetwork

  pgAdmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    depends_on:
      - GamePerfDB
    restart: always
    ports:
      - '5555:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=password
    networks:
      - testNetwork